"""empty message

Revision ID: 884bc60e82e2
Revises: 6df9d76f28a4
Create Date: 2023-06-03 06:30:20.585157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884bc60e82e2'
down_revision = '6df9d76f28a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
